
server:
    context-path: /student


spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/ust
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
